name: Deploy

on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  TERRAFORM_VERSION: "1.14.8"
  NODE_VERSION: "24"

jobs:
  build-and-deploy:
    name: Build & Deploy
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS Credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        id: install-dependencies
        run: npm ci

      - name: Build OpenNext
        id: build-opennext
        run: npx @opennextjs/aws build

      - name: Setup Terraform
        id: setup-terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # 4.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        id: terraform-init
        working-directory: infra
        run: terraform init -reconfigure

      - name: Terraform Apply
        id: terraform-apply
        working-directory: infra
        run: |
          terraform apply -auto-approve
