name: Prettier

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          cache: npm

      - name: Install dependencies
        id: install-dependencies
        run: npm ci

      - name: Run Prettier
        id: run-prettier
        run: npx prettier --check .
