name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.TERRANEXT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.TERRANEXT_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          release-type: node
          token: ${{ steps.app-token.outputs.token }}
