name: Validate

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Terraform
        id: terraform-setup
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # 4.0.0

      - name: Check formatting
        id: terraform-format
        working-directory: infra
        run: terraform fmt -check -recursive

      - name: Initialize
        id: terraform-init
        working-directory: infra
        run: terraform init -backend=false

      - name: Validate
        id: terraform-validate
        working-directory: infra
        run: terraform validate
